jobs:
- job: Build
  displayName: 'Build'
  timeoutInMinutes: 120
  pool:
    vmImage: windows-2025

  variables:
    winUIVersion: '1.8.250906003'
    foundationVersion: '1.8.250906002'
    interactiveExperiencesVersion: '1.8.250906004'
    webview2Version: '1.0.3485.44'
    arch: ${{ parameters.arch }}

  steps:
  - task: BatchScript@1
    inputs:
      filename: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat'
      arguments: '-arch=amd64'
      modifyEnvironment: true
    displayName: 'Initialize Visual Studio Environment'

  - script: |
      choco install sentry-cli
    displayName: 'Install Sentry CLI'
    condition: ne( variables['VERSION'], '' )

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: 'install Microsoft.WindowsAppSDK.WinUI -Version $(winUIVersion) -OutputDirectory $(System.DefaultWorkingDirectory)\WindowsAppSDK'
    displayName: 'Download WindowsAppSDK'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: 'install Microsoft.Web.WebView2 -Version $(webview2Version) -OutputDirectory $(System.DefaultWorkingDirectory)\WindowsAppSDK'
    displayName: 'Download WebView2'

  - script: |
      winmdidl /nologo /outdir:. ../../Microsoft.WindowsAppSDK.InteractiveExperiences.$(interactiveExperiencesVersion)/metadata/10.0.18362.0/Microsoft.Foundation.winmd
      winmdidl /nologo /outdir:. ../../Microsoft.WindowsAppSDK.InteractiveExperiences.$(interactiveExperiencesVersion)/metadata/10.0.18362.0/Microsoft.Graphics.winmd
      winmdidl /nologo /outdir:. ../../Microsoft.WindowsAppSDK.InteractiveExperiences.$(interactiveExperiencesVersion)/metadata/10.0.18362.0/Microsoft.UI.winmd
      winmdidl /nologo /outdir:. ../metadata/Microsoft.UI.Text.winmd
      winmdidl /nologo /outdir:. ../../Microsoft.Web.WebView2.$(webview2Version)/lib/Microsoft.Web.WebView2.Core.winmd
      winmdidl /nologo /outdir:. ../../Microsoft.WindowsAppSDK.Foundation.$(foundationVersion)/metadata/Microsoft.Windows.ApplicationModel.Resources.winmd
      winmdidl /nologo /outdir:. ../metadata/Microsoft.UI.Xaml.winmd
      for %%i in (*.idl) do (
        midlrt %%i /metadata_dir C:\Windows\System32\WinMetadata /ns_prefix /nomidl
      )
    workingDirectory: '$(System.DefaultWorkingDirectory)\WindowsAppSDK\Microsoft.WindowsAppSDK.WinUI.$(winUIVersion)\include'
    displayName: 'Make Header Files'

  - script: |
      mkdir win10-$(arch)
      move ..\..\Microsoft.WindowsAppSDK.Foundation.$(foundationVersion)\lib\native\$(arch)\* win10-$(arch)\
    workingDirectory: '$(System.DefaultWorkingDirectory)\WindowsAppSDK\Microsoft.WindowsAppSDK.WinUI.$(winUIVersion)\lib'
    displayName: 'Move Libs'

  - script: |
      call build.cmd $(arch)
    env:
      WINDOWSAPP_SDK_DIR: '$(System.DefaultWorkingDirectory)\WindowsAppSDK\Microsoft.WindowsAppSDK.WinUI.$(winUIVersion)'
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)\angle-$(arch)'
      ArtifactName: 'angle-$(arch)'
      publishLocation: Container

  - script: |
      sentry-cli debug-files upload -o celestia-vs -p windows --auth-token $(SENTRY_AUTH_TOKEN) --include-sources bin\libGLESv2.pdb
      sentry-cli debug-files upload -o celestia-vs -p windows --auth-token $(SENTRY_AUTH_TOKEN) --include-sources bin\libEGL.pdb
    workingDirectory: '$(System.DefaultWorkingDirectory)\angle-$(arch)'
    displayName: 'Upload Symbols'
    condition: ne( variables['VERSION'], '' )
