jobs:
- job: Package
  displayName: 'Package'
  pool:
    vmImage: windows-2025

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download x64 Artifacts'
    inputs:
      artifactName: 'angle-x64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DownloadBuildArtifacts@0
    displayName: 'Download arm64 Artifacts'
    inputs:
      artifactName: 'angle-arm64'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: 'pack ANGLE.nuspec -Version $(VERSION)'
    displayName: 'Package'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)\ANGLE.$(VERSION).nupkg'
      ArtifactName: 'angle'
      publishLocation: Container
